// ToolStand — Tools data (108 tools)
// Loaded async so it doesn't block the critical rendering path
const TOOLS = [
  { id:"qr-code", name:"QR Code Generator & Scanner", desc:"Create and scan QR codes instantly. No app needed.", icon:"📱", tags:["generator","utility"], ready:true },
  { id:"spirit-level", name:"Spirit Level", desc:"Use your phone as a bubble level. Perfect for hanging pictures.", icon:"📐", tags:["utility"], ready:true },
  { id:"pomodoro", name:"Pomodoro Timer", desc:"Focus timer with clean design. No ads interrupting your flow.", icon:"🍅", tags:["productivity"], ready:true },
  { id:"metronome", name:"Metronome", desc:"Precise rhythm tool for musicians. No subscription paywalls.", icon:"🎵", tags:["productivity"], ready:true },
  { id:"decibel-meter", name:"Decibel Meter", desc:"Measure sound levels. Great for classrooms and events.", icon:"🔊", tags:["utility"], ready:true },
  { id:"decision-wheel", name:"Decision Wheel", desc:"Spin the wheel with custom options. Fair, fast, and free.", icon:"🎡", tags:["game","utility"], ready:true },
  { id:"sleep-sounds", name:"Sleep Sounds & White Noise", desc:"Mix rain, fire, ocean, and white noise. Fall asleep faster.", icon:"🌙", tags:["utility"], ready:true },
  { id:"dead-pixel-test", name:"Dead Pixel Test", desc:"Full-screen color test for your screen. No ads during the test.", icon:"🖥️", tags:["utility"], ready:true },
  { id:"due-date-calculator", name:"Pregnancy Due Date Calculator", desc:"Estimate your due date instantly. No sign-ups.", icon:"👶", tags:["calculator"], ready:true },
  { id:"signature-generator", name:"Signature Generator", desc:"Create a beautiful handwritten signature. Download as PNG.", icon:"✍️", tags:["generator"], ready:true },
  { id:"bmi-calculator", name:"BMI Calculator", desc:"Body Mass Index calculator. Instant results, no health data stored.", icon:"⚖️", tags:["calculator"], ready:true },
  { id:"age-calculator", name:"Age Calculator", desc:"Calculate exact age in years, months, and days.", icon:"🎂", tags:["calculator"], ready:true },
  { id:"password-generator", name:"Password Generator", desc:"Generate strong, random passwords. Configurable length.", icon:"🔐", tags:["generator"], ready:true },
  { id:"word-counter", name:"Word & Character Counter", desc:"Count words, characters, sentences, and reading time.", icon:"📝", tags:["productivity"], ready:true },
  { id:"base64", name:"Base64 Encoder & Decoder", desc:"Encode and decode Base64 strings. Essential developer utility.", icon:"🔣", tags:["generator","converter"], ready:true },
  { id:"color-converter", name:"Color Code Converter", desc:"Convert HEX to RGB and HSL. Pick colors and copy codes.", icon:"🎨", tags:["converter"], ready:true },
  { id:"countdown", name:"Countdown Timer", desc:"Set a date and time, get a live countdown. Embeddable.", icon:"⏳", tags:["productivity"], ready:true },
  { id:"dpi-calculator", name:"DPI & PPI Calculator", desc:"Calculate screen pixel density. For designers and developers.", icon:"📺", tags:["calculator"], ready:true },
  { id:"roman-numerals", name:"Roman Numeral Converter", desc:"Convert numbers to Roman numerals and back.", icon:"🏛️", tags:["converter"], ready:true },
  { id:"tip-calculator", name:"Tip Calculator", desc:"Calculate tips and split bills. Works worldwide.", icon:"💵", tags:["calculator"], ready:true },
  { id:"compound-interest", name:"Compound Interest Calculator", desc:"See how your money grows with compound interest. Charts.", icon:"📈", tags:["calculator"], ready:true },
  { id:"dividend-calculator", name:"Dividend Reinvestment Calculator", desc:"Calculate dividend returns with reinvestment and tax.", icon:"💰", tags:["calculator"], ready:true },
  { id:"minesweeper", name:"Minesweeper", desc:"Classic minesweeper. 3 difficulty levels. Flag, reveal, win.", icon:"💣", tags:["game"], ready:true },
  { id:"snake-game", name:"Snake Game", desc:"Classic snake game. Eat, grow, beat your high score.", icon:"🐍", tags:["game"], ready:true },
  { id:"reaction-time", name:"Reaction Time Test", desc:"Test your reflexes. High-precision timing via performance.now().", icon:"⚡", tags:["game","utility"], ready:true },
  { id:"tone-generator", name:"Frequency Generator & Tone Tool", desc:"Pure tones 20Hz-20kHz. Water extraction mode included.", icon:"🎛️", tags:["utility"], ready:true },
  { id:"diff-checker", name:"Text Diff Checker", desc:"Compare two texts side by side. Color-coded LCS diff.", icon:"📝", tags:["productivity"], ready:true },
  { id:"video-script-timer", name:"Video Hook & Script Timer", desc:"Calculate video duration from script. WPM slider, hook detection.", icon:"🎬", tags:["productivity"], ready:true },
  { id:"youtube-title-generator", name:"YouTube Title & Tag Generator", desc:"Generate YouTube titles and tags from keywords.", icon:"📋", tags:["generator"], ready:true },
  { id:"token-counter", name:"AI Token Counter & Cost Estimator", desc:"Count tokens, estimate API costs for 12 models.", icon:"🤖", tags:["productivity"], ready:true },
  { id:"json-formatter", name:"JSON Formatter & Validator", desc:"Format, validate, minify JSON. Error line detection.", icon:"{ }", tags:["converter"], ready:true },
  { id:"trade-risk-calculator", name:"Trade Risk & Break-Even Calc", desc:"Break-even price with commission. BIST, Binance presets.", icon:"📊", tags:["calculator"], ready:true },
  { id:"dca-calculator", name:"DCA Calculator", desc:"Dollar Cost Averaging. Add buys, see real average cost.", icon:"📉", tags:["calculator"], ready:true },
  { id:"keto-calculator", name:"Keto & Macro Calculator", desc:"Calculate keto macros. BMR, TDEE, doughnut chart.", icon:"🥑", tags:["calculator"], ready:true },
  { id:"uuid-generator", name:"UUID Generator", desc:"Generate UUID v4 identifiers. Browser crypto API.", icon:"🆔", tags:["generator"], ready:true },
  { id:"jwt-decoder", name:"JWT Decoder", desc:"Decode JWT tokens. View header, payload, expiration.", icon:"🔐", tags:["converter"], ready:true },
  { id:"timestamp-converter", name:"Unix Timestamp Converter", desc:"Convert Unix timestamps to dates and back. Bidirectional.", icon:"🕐", tags:["converter"], ready:true },
  { id:"url-encoder", name:"URL Encoder & Decoder", desc:"Encode/decode URL strings. Percent-encoding tool.", icon:"🔗", tags:["converter"], ready:true },
  { id:"html-entity-encoder", name:"HTML Entity Encoder & Decoder", desc:"Encode/decode HTML entities. XSS prevention.", icon:"📝", tags:["converter"], ready:true },
  { id:"case-converter", name:"Case Converter", desc:"UPPER, lower, camelCase, snake_case, 8 formats.", icon:"🔤", tags:["converter"], ready:true },
  { id:"base-converter", name:"Number Base Converter", desc:"Binary, octal, decimal, hex. Real-time conversion.", icon:"🔢", tags:["converter"], ready:true },
  { id:"stopwatch", name:"Stopwatch", desc:"Online stopwatch with lap timing. Millisecond precision.", icon:"⏱️", tags:["productivity"], ready:true },
  { id:"date-difference", name:"Date Difference Calculator", desc:"Days between dates. Business days, years, weeks.", icon:"📅", tags:["calculator"], ready:true },
  { id:"utm-builder", name:"UTM Builder", desc:"Build UTM campaign URLs. Source, medium, campaign.", icon:"📊", tags:["generator"], ready:true },
  { id:"robots-txt-generator", name:"Robots.txt Generator", desc:"Generate robots.txt. Allow/block crawlers.", icon:"🤖", tags:["generator"], ready:true },
  { id:"meta-tag-generator", name:"Meta Tag Generator", desc:"Generate SEO meta, Open Graph, Twitter Card tags.", icon:"🏷️", tags:["generator"], ready:true },
  { id:"color-palette-generator", name:"Color Palette Generator", desc:"Complementary, analogous, triadic, monochrome palettes.", icon:"🎨", tags:["generator"], ready:true },
  { id:"lorem-ipsum", name:"Lorem Ipsum Generator", desc:"Placeholder text. Paragraphs or words. HTML output.", icon:"📄", tags:["generator"], ready:true },
  { id:"cron-builder", name:"Cron Expression Builder", desc:"Visual cron builder. Human-readable. Presets included.", icon:"⏰", tags:["productivity"], ready:true },
  { id:"hash-generator", name:"Hash Generator", desc:"SHA-256, SHA-1, SHA-512. Web Crypto API.", icon:"🔐", tags:["generator"], ready:true },
  { id:"regex-tester", name:"Regex Tester", desc:"Test regex in real-time. Highlight matches, groups.", icon:"🔍", tags:["productivity"], ready:true },
  { id:"markdown-previewer", name:"Markdown Previewer", desc:"Live Markdown preview. Write left, see rendered HTML right.", icon:"📝", tags:["productivity"], ready:true },
  { id:"password-strength-checker", name:"Password Strength Checker", desc:"Entropy score, crack time, improvement tips.", icon:"🔒", tags:["utility"], ready:true },
  { id:"unit-converter", name:"Unit Converter", desc:"Length, weight, temp, area, volume, speed. All in one.", icon:"📏", tags:["converter"], ready:true },
  { id:"readability-checker", name:"Readability Score Checker", desc:"Flesch-Kincaid score, grade level, word statistics.", icon:"📖", tags:["productivity"], ready:true },
  { id:"timezone-converter", name:"Time Zone Converter", desc:"Compare current time across cities worldwide.", icon:"🌍", tags:["utility"], ready:true },
  { id:"json-compare", name:"JSON Compare", desc:"Compare two JSON objects. Find added/removed/changed keys.", icon:"🔍", tags:["converter"], ready:true },
  { id:"water-intake", name:"Water Intake Calculator", desc:"Daily water needs based on weight, activity, climate.", icon:"💧", tags:["calculator"], ready:true },
  { id:"whats-my-ip", name:"What Is My IP Address", desc:"Check your public IPv4 & IPv6, ISP, and location instantly.", icon:"🌐", tags:["developer","utility"], ready:true },
  { id:"gradient-generator", name:"Gradient Generator", desc:"CSS gradients: linear, radial, conic. Copy CSS code.", icon:"🎨", tags:["generator"], ready:true },
  { id:"json-schema-generator", name:"JSON Schema Generator", desc:"Generate JSON Schema from JSON. Auto-detects types.", icon:"📋", tags:["converter"], ready:true },
  { id:"yaml-validator", name:"YAML Validator", desc:"Validate YAML, convert to JSON. Error line detection.", icon:"📄", tags:["converter"], ready:true },
  { id:"sql-formatter", name:"SQL Formatter", desc:"Format SQL. MySQL, PostgreSQL, SQLite. Beautify/minify.", icon:"🗄️", tags:["converter"], ready:true },
  { id:"barcode-generator", name:"Barcode Generator", desc:"CODE128, EAN-13, UPC barcodes. Download SVG/PNG.", icon:"📊", tags:["generator"], ready:true },
  { id:"scientific-calculator", name:"Scientific Calculator", desc:"Trig, log, sqrt, power. Expression input with history.", icon:"🧮", tags:["calculator"], ready:true },
  { id:"temperature-tracker", name:"Temperature Tracker", desc:"Track body temp. Chart, CSV export. Fever alerts.", icon:"🌡️", tags:["utility"], ready:true },
  { id:"regex-explainer", name:"Regex Explainer", desc:"Translate regex to human language. Token-by-token explanation.", icon:"🔍", tags:["utility","developer"], ready:true },
  { id:"xml-formatter", name:"XML Formatter & Validator", desc:"Format & validate XML. DOMParser error detection.", icon:"📄", tags:["formatter","developer"], ready:true },
  { id:"xml-json-converter", name:"XML ↔ JSON Converter", desc:"Bidirectional XML ↔ JSON conversion. Recursive mapping.", icon:"🔄", tags:["converter","developer"], ready:true },
  { id:"csv-json-converter", name:"CSV ↔ JSON Converter", desc:"CSV ↔ JSON converter. Smart parsing with PapaParse.", icon:"📊", tags:["converter","developer"], ready:true },
  { id:"jsonpath-tester", name:"JSONPath Tester", desc:"Evaluate JSONPath queries. Select data from JSON.", icon:"🎯", tags:["developer","utility"], ready:true },
  { id:"serp-preview", name:"SERP Preview Tool", desc:"Google SERP preview. Title 60, description 160 chars.", icon:"🔎", tags:["seo","utility"], ready:true },
  { id:"inflation-calculator", name:"Inflation Calculator", desc:"Calculate inflation impact. Future value of money.", icon:"💸", tags:["calculator","finance"], ready:true },
  { id:"random-number", name:"Random Number Generator", desc:"Cryptographic random numbers. Dice, lottery, unique picks.", icon:"🎲", tags:["generator","utility"], ready:true },
  { id:"aspect-ratio", name:"Aspect Ratio Calculator", desc:"Aspect ratio calculator. YouTube, Instagram, TikTok presets.", icon:"📐", tags:["calculator","utility"], ready:true },
  { id:"text-encryptor", name:"Text Encryptor / Decryptor", desc:"AES-256-GCM encryption. Password-protected messages.", icon:"🔐", tags:["security","utility"], ready:true },
  { id:"ssh-key-generator", name:"SSH Key Generator", desc:"Generate SSH key pairs. RSA, ECDSA. PEM format.", icon:"🔑", tags:["security","developer"], ready:true },
  { id:"bpm-tap", name:"BPM Tap Tempo", desc:"Tap tempo BPM finder. Tap button or press spacebar.", icon:"🥁", tags:["utility","music"], ready:true },
  { id:"og-preview", name:"Open Graph Preview", desc:"Social media link preview. Facebook, Twitter, LinkedIn.", icon:"👁️", tags:["seo","utility"], ready:true },
  { id:"image-resizer", name:"Image Resizer & Compressor", desc:"Resize & compress images. Canvas API, no upload.", icon:"🖼️", tags:["utility","converter"], ready:true },
  { id:"image-converter", name:"Image Format Converter", desc:"PNG, JPEG, WebP conversion. Batch processing support.", icon:"🔄", tags:["converter","utility"], ready:true },
  { id:"loan-calculator", name:"Loan & Mortgage Calculator", desc:"Loan calculator. Monthly payment, amortization, early payoff.", icon:"🏦", tags:["calculator","finance"], ready:true },
  { id:"calorie-calculator", name:"Calorie & TDEE Calculator", desc:"Daily calorie needs, TDEE, macros. BMR calculation.", icon:"🔥", tags:["calculator","health"], ready:true },
  { id:"color-blindness", name:"Color Blindness Simulator", desc:"Color blindness simulator. 4 types, Canvas LMS matrix.", icon:"👁️", tags:["utility","accessibility"], ready:true },
  { id:"pace-calculator", name:"Pace & Running Calculator", desc:"Running pace, time, distance. 5K, 10K, marathon splits.", icon:"🏃", tags:["calculator","health"], ready:true },
  { id:"pomodoro-task", name:"Pomodoro + Task Tracker", desc:"Pomodoro timer + task list. Progress tracking.", icon:"✅", tags:["productivity"], ready:true },
  { id:"currency-converter", name:"Currency Converter", desc:"Live exchange rates. Frankfurter API, 7-day chart.", icon:"💱", tags:["converter","finance"], ready:true },
  { id:"function-plotter", name:"Function Graph Plotter", desc:"Math function graphing. sin, cos, x², multi-function.", icon:"📈", tags:["calculator","education"], ready:true },
  { id:"invoice-generator", name:"Invoice Generator", desc:"Create invoices, print-ready template. Export via print.", icon:"🧾", tags:["generator","productivity"], ready:true },
  { id:"wordle-solver", name:"Wordle Solver", desc:"Wordle solver. Letter filtering, 2000+ words.", icon:"🟩", tags:["game","utility"], ready:true },
  { id:"pdf-merge", name:"PDF Merge", desc:"Combine multiple PDFs into one. Drag-and-drop, reorder, instant download.", icon:"📎", tags:["pdf","utility"], ready:true },
  { id:"pdf-split", name:"PDF Split", desc:"Split PDFs by page range. Extract individual pages or ranges.", icon:"✂️", tags:["pdf","utility"], ready:true },
  { id:"image-to-pdf", name:"Image to PDF", desc:"Convert JPG, PNG, WebP images to PDF. A4/Letter, margins.", icon:"🖼️", tags:["pdf","converter"], ready:true },
  { id:"pdf-to-image", name:"PDF to Image", desc:"Convert PDF pages to PNG, JPG, or WebP images. High quality.", icon:"📄", tags:["pdf","converter"], ready:true },
  { id:"schema-markup-generator", name:"Schema Markup Generator", desc:"Generate JSON-LD schema. Organization, Product, FAQ, Article, more.", icon:"🏗️", tags:["seo","generator"], ready:true },
  { id:"faq-schema-generator", name:"FAQ Schema Generator", desc:"Create Google FAQ rich results. Question-answer pairs, copy code.", icon:"❓", tags:["seo","generator"], ready:true },
  { id:"savings-calculator", name:"Savings Calculator", desc:"Future value of savings. Compound growth with Chart.js visualization.", icon:"🐖", tags:["calculator","finance"], ready:true },
  { id:"retirement-calculator", name:"Retirement Calculator", desc:"Estimate retirement fund and monthly income. 4% rule, growth chart.", icon:"👴", tags:["calculator","finance"], ready:true },
  { id:"body-fat-calculator", name:"Body Fat Calculator", desc:"US Navy body fat % formula. Gender-specific, fitness assessment.", icon:"💪", tags:["calculator","health"], ready:true },
  { id:"svg-optimizer", name:"SVG Optimizer", desc:"Minify and clean SVG code. Remove metadata, comments, whitespace.", icon:"📐", tags:["design","utility"], ready:true },
  { id:"css-box-shadow", name:"CSS Box Shadow Generator", desc:"Design box shadows visually. Adjust offset, blur, spread, color. Live preview. Copy CSS.", icon:"🎨", tags:["design","utility"], ready:true },
  { id:"css-border-radius", name:"CSS Border Radius Generator", desc:"Generate border-radius visually. Control each corner individually. px or %. Copy CSS.", icon:"⭕", tags:["design","utility"], ready:true },
  { id:"css-clamp-generator", name:"CSS Clamp Generator", desc:"Generate CSS clamp() for fluid typography and spacing. Min, preferred, max. Copy instantly.", icon:"📐", tags:["developer","utility"], ready:true },
  { id:"json-minifier", name:"JSON Minifier", desc:"Minify and compress JSON. Strip whitespace, reduce file size. Size comparison stats.", icon:"📦", tags:["developer","utility"], ready:true },

  { id:"json-to-java", name:"JSON to Java POJO/DTO Converter", desc:"Convert JSON to Java POJO classes with Lombok, Jackson, nested objects. Free online converter, no sign-up.", icon:"☕", tags:["developer","generator"], ready:true },
  { id:"ai-prompt-builder", name:"AI Prompt Builder & Optimizer", desc:"Build structured prompts for ChatGPT, Claude, Midjourney. Role, tone, format controls. Free and instant.", icon:"🤖", tags:["productivity","generator"], ready:true },
  { id:"dockerfile-generator", name:"Dockerfile & Docker Compose Generator", desc:"Generate Dockerfile and compose files for Node, Python, Go, Java. Pick DB, ports, env vars. No Docker experience needed.", icon:"🐳", tags:["developer","generator"], ready:true },
  { id:"meta-tag-preview", name:"Meta Tag & SERP Preview Generator", desc:"Preview Google search results and social cards. Generate meta tags with live SERP simulator. Free SEO tool.", icon:"🔍", tags:["seo","generator"], ready:true },
  { id:"markdown-table", name:"Markdown Table Generator & CSV Converter", desc:"Create Markdown tables visually or paste CSV. Align columns, export to HTML. Works with GitHub Flavored Markdown.", icon:"📊", tags:["productivity","formatter"], ready:true },
];
